stage.set_background("park")
boy = codesters.Sprite("person12")
boy.go_to(-285, -70)
stage.wait(2)

boy.move_right(30)
boy.move_right(30)
boy.move_right(30)
boy.move_right(30)
boy.move_right(30)
boy.say("I'm so bored", 2)
boy.say("Maybe the park will be interesting.", 2)
stage.wait(1)

alien = codesters.Sprite("alien2")
alien.go_to(90, 400)
alien.move_down(50)
alien.move_down(50)
alien.move_down(50)
alien.move_down(50)
alien.move_down(50)
alien.move_down(50)
alien.move_down(50)
alien.move_down(50)
alien.move_down(50)
alien.move_down(50)
alien.say("Hey there! I'm new in town!", 3)
boy.say("Wow!")